ALTER TABLE seasons ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 1 AFTER status;
ALTER TABLE seasons ADD COLUMN IF NOT EXISTS updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER payload_json;
ALTER TABLE mesocycles ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 1 AFTER primary_adaptation;
ALTER TABLE mesocycles ADD COLUMN IF NOT EXISTS updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER payload_json;
ALTER TABLE microcycles ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 1 AFTER focus;
ALTER TABLE microcycles ADD COLUMN IF NOT EXISTS updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER payload_json;
ALTER TABLE adaptation_decisions ADD COLUMN IF NOT EXISTS applied_at DATETIME(6) NULL AFTER created_at;
ALTER TABLE adaptation_decisions ADD COLUMN IF NOT EXISTS applied_by_subject VARCHAR(191) NULL AFTER applied_at;
